name: mazzari
description: تطبيق أرشفة فواتير المزارع
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  intl: ^0.20.0
  fl_chart: ^0.68.0
  image_picker: ^1.0.7
  share_plus: ^7.2.2
  csv: ^6.0.0
  pdf: ^3.10.7
  printing: ^5.12.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
